#pragma once

#include "mana.hpp"

#include <unordered_map>
#include <string>


enum ManaSourceSignature {
    Basic,
    Surveil,
    Gain,
    Fast,
    Pain,
    FetchableTapped,
    Slow,
    Reveal,
    KaldheimSnow,
    Pathway,
    Scry,
    Shock,
    Guildgate,
    Check,
    Generic,
    Fetch,
    Artifact,
    Filter,
    Bounce,
    Battlebond,
    OdysseyFilter,
    Dual,
    TriCycle,
    Tri,
    Talisman,
    Signet,
    Medallion,
    Cluestone,
    Diamond,
    Keyrune,
    Locket,
    Obelisk,
    Banner,
    Crystal,
    Monument,
    Borderpost,
    Totem,
    Cameo,
    Ramos,
    AmonkhetMonument,
    TriSacFetch,
    DesertPing
};

static std::unordered_map<std::string, ManaSourceSignature> const string_to_ms = {
    {"Basic", ManaSourceSignature::Basic},
    {"Surveil", ManaSourceSignature::Surveil},
    {"Gain", ManaSourceSignature::Gain},
    {"Fast", ManaSourceSignature::Fast},
    {"Pain", ManaSourceSignature::Pain},
    {"FetchableTapped", ManaSourceSignature::FetchableTapped},
    {"Slow", ManaSourceSignature::Slow},
    {"Reveal", ManaSourceSignature::Reveal},
    {"KaldheimSnow", ManaSourceSignature::KaldheimSnow},
    {"Pathway", ManaSourceSignature::Pathway},
    {"Scry", ManaSourceSignature::Scry},
    {"Shock", ManaSourceSignature::Shock},
    {"Guildgate", ManaSourceSignature::Guildgate},
    {"Check", ManaSourceSignature::Check},
    {"Generic", ManaSourceSignature::Generic},
    {"Fetch", ManaSourceSignature::Fetch},
    {"Artifact", ManaSourceSignature::Artifact},
    {"Filter", ManaSourceSignature::Filter},
    {"Bounce", ManaSourceSignature::Bounce},
    {"Battlebond", ManaSourceSignature::Battlebond},
    {"OdysseyFilter", ManaSourceSignature::OdysseyFilter},
    {"Dual", ManaSourceSignature::Dual},
    {"TriCycle", ManaSourceSignature::TriCycle},
    {"Tri", ManaSourceSignature::Tri},
    {"Talisman", ManaSourceSignature::Talisman},
    {"Signet", ManaSourceSignature::Signet},
    {"Medallion", ManaSourceSignature::Medallion},
    {"Cluestone", ManaSourceSignature::Cluestone},
    {"Diamond", ManaSourceSignature::Diamond},
    {"Keyrune", ManaSourceSignature::Keyrune},
    {"Locket", ManaSourceSignature::Locket},
    {"Obelisk", ManaSourceSignature::Obelisk},
    {"Banner", ManaSourceSignature::Banner},
    {"Crystal", ManaSourceSignature::Crystal},
    {"Monument", ManaSourceSignature::Monument},
    {"Borderpost", ManaSourceSignature::Borderpost},
    {"Totem", ManaSourceSignature::Totem},
    {"Cameo", ManaSourceSignature::Cameo},
    {"Ramos", ManaSourceSignature::Ramos},
    {"AmonkhetMonument", ManaSourceSignature::AmonkhetMonument},
    {"TriSacFetch", ManaSourceSignature::TriSacFetch},
    {"DesertPing", ManaSourceSignature::DesertPing}
};

ManaSourceSignature getManaSourceSignature(std::string name);