#pragma once

#include "mana.hpp"
#include "land.hpp"
#include "landcycle.hpp"

const Land lands[] = {
    {"Tranquil Cove", ColorCombination::AZORIUS, ManaSourceSignature::Gain},
    {"Dismal Backwater", ColorCombination::DIMIR, ManaSourceSignature::Gain},
    {"Bloodfell Caves", ColorCombination::RAKDOS, ManaSourceSignature::Gain},
    {"Rugged Highlands", ColorCombination::GRUUL, ManaSourceSignature::Gain},
    {"Blossoming Sands", ColorCombination::SELESNYA, ManaSourceSignature::Gain},
    {"Scoured Barrens", ColorCombination::ORZHOV, ManaSourceSignature::Gain},
    {"Swiftwater Cliffs", ColorCombination::IZZET, ManaSourceSignature::Gain},
    {"Jungle Hollow", ColorCombination::GOLGARI, ManaSourceSignature::Gain},
    {"Wind-Scarred Crag", ColorCombination::BOROS, ManaSourceSignature::Gain},
    {"Thornwood Falls", ColorCombination::SIMIC, ManaSourceSignature::Gain},
    {"Seachrome Coast", ColorCombination::AZORIUS, ManaSourceSignature::Fast},
    {"Darkslick Shores", ColorCombination::DIMIR, ManaSourceSignature::Fast},
    {"Blackcleave Cliffs", ColorCombination::RAKDOS, ManaSourceSignature::Fast},
    {"Copperline Gorge", ColorCombination::GRUUL, ManaSourceSignature::Fast},
    {"Razorverge Thicket", ColorCombination::SELESNYA, ManaSourceSignature::Fast},
    {"Concealed Courtyard", ColorCombination::ORZHOV, ManaSourceSignature::Fast},
    {"Spirebluff Canal", ColorCombination::IZZET, ManaSourceSignature::Fast},
    {"Blooming Marsh", ColorCombination::GOLGARI, ManaSourceSignature::Fast},
    {"Inspiring Vantage", ColorCombination::BOROS, ManaSourceSignature::Fast},
    {"Botanical Sanctum", ColorCombination::SIMIC, ManaSourceSignature::Fast},
    {"Adarkar Wastes", ColorCombination::AZORIUS, ManaSourceSignature::Pain},
    {"Underground River", ColorCombination::DIMIR, ManaSourceSignature::Pain},
    {"Sulfurous Springs", ColorCombination::RAKDOS, ManaSourceSignature::Pain},
    {"Karplusan Forest", ColorCombination::GRUUL, ManaSourceSignature::Pain},
    {"Brushland", ColorCombination::SELESNYA, ManaSourceSignature::Pain},
    {"Caves of Koilos", ColorCombination::ORZHOV, ManaSourceSignature::Pain},
    {"Shivan Reef", ColorCombination::IZZET, ManaSourceSignature::Pain},
    {"Llanowar Wastes", ColorCombination::GOLGARI, ManaSourceSignature::Pain},
    {"Battlefield Forge", ColorCombination::BOROS, ManaSourceSignature::Pain},
    {"Yavimaya Coast", ColorCombination::SIMIC, ManaSourceSignature::Pain},
    {"Idyllic Beachfront", ColorCombination::AZORIUS, ManaSourceSignature::FetchableTapped},
    {"Contaminated Aquifer", ColorCombination::DIMIR, ManaSourceSignature::FetchableTapped},
    {"Geothermal Bog", ColorCombination::RAKDOS, ManaSourceSignature::FetchableTapped},
    {"Wooded Ridgeline", ColorCombination::GRUUL, ManaSourceSignature::FetchableTapped},
    {"Radiant Grove", ColorCombination::SELESNYA, ManaSourceSignature::FetchableTapped},
    {"Sunlit Marsh", ColorCombination::ORZHOV, ManaSourceSignature::FetchableTapped},
    {"Molten Tributary", ColorCombination::IZZET, ManaSourceSignature::FetchableTapped},
    {"Haunted Mire", ColorCombination::GOLGARI, ManaSourceSignature::FetchableTapped},
    {"Sacred Peaks", ColorCombination::BOROS, ManaSourceSignature::FetchableTapped},
    {"Tangled Islet", ColorCombination::SIMIC, ManaSourceSignature::FetchableTapped},
    {"Deserted Beach", ColorCombination::AZORIUS, ManaSourceSignature::Slow},
    {"Shipwreck Marsh", ColorCombination::DIMIR, ManaSourceSignature::Slow},
    {"Haunted Ridge", ColorCombination::RAKDOS, ManaSourceSignature::Slow},
    {"Rockfall Vale", ColorCombination::GRUUL, ManaSourceSignature::Slow},
    {"Overgrown Farmland", ColorCombination::SELESNYA, ManaSourceSignature::Slow},
    {"Shattered Sanctum", ColorCombination::ORZHOV, ManaSourceSignature::Slow},
    {"Stormcarved Coast", ColorCombination::IZZET, ManaSourceSignature::Slow},
    {"Deathcap Glade", ColorCombination::GOLGARI, ManaSourceSignature::Slow},
    {"Sundown Pass", ColorCombination::BOROS, ManaSourceSignature::Slow},
    {"Dreamroot Cascade", ColorCombination::SIMIC, ManaSourceSignature::Slow},
    {"Shineshadow Snarl", ColorCombination::ORZHOV, ManaSourceSignature::Reveal},
    {"Frostboil Snarl", ColorCombination::IZZET, ManaSourceSignature::Reveal},
    {"Necroblossom Snarl", ColorCombination::GOLGARI, ManaSourceSignature::Reveal},
    {"Furycalm Snarl", ColorCombination::BOROS, ManaSourceSignature::Reveal},
    {"Vineglimmer Snarl", ColorCombination::SIMIC, ManaSourceSignature::Reveal},
    {"Glacial Floodplain", ColorCombination::AZORIUS, ManaSourceSignature::KaldheimSnow},
    {"Ice Tunnel", ColorCombination::DIMIR, ManaSourceSignature::KaldheimSnow},
    {"Sulfurous Mire", ColorCombination::RAKDOS, ManaSourceSignature::KaldheimSnow},
    {"Highland Forest", ColorCombination::GRUUL, ManaSourceSignature::KaldheimSnow},
    {"Arctic Treeline", ColorCombination::SELESNYA, ManaSourceSignature::KaldheimSnow},
    {"Snowfield Sinkhole", ColorCombination::ORZHOV, ManaSourceSignature::KaldheimSnow},
    {"Volatile Fjord", ColorCombination::IZZET, ManaSourceSignature::KaldheimSnow},
    {"Woodland Chasm", ColorCombination::GOLGARI, ManaSourceSignature::KaldheimSnow},
    {"Alpine Meadow", ColorCombination::BOROS, ManaSourceSignature::KaldheimSnow},
    {"Rimewood Falls", ColorCombination::SIMIC, ManaSourceSignature::KaldheimSnow},
    {"Hengegate Pathway // Mistgate Pathway", ColorCombination::AZORIUS, ManaSourceSignature::Pathway},
    {"Clearwater Pathway // Murkwater Pathway", ColorCombination::DIMIR, ManaSourceSignature::Pathway},
    {"Blightstep Pathway // Searstep Pathway", ColorCombination::RAKDOS, ManaSourceSignature::Pathway},
    {"Cragcrown Pathway // Timbercrown Pathway", ColorCombination::GRUUL, ManaSourceSignature::Pathway},
    {"Branchloft Pathway // Boulderloft Pathway", ColorCombination::SELESNYA, ManaSourceSignature::Pathway},
    {"Brightclimb Pathway // Grimclimb Pathway", ColorCombination::ORZHOV, ManaSourceSignature::Pathway},
    {"Riverglide Pathway // Lavaglide Pathway", ColorCombination::IZZET, ManaSourceSignature::Pathway},
    {"Darkbore Pathway // Slitherbore Pathway", ColorCombination::GOLGARI, ManaSourceSignature::Pathway},
    {"Needleverge Pathway // Pillarverge Pathway", ColorCombination::BOROS, ManaSourceSignature::Pathway},
    {"Barkchannel Pathway // Tidechannel Pathway", ColorCombination::SIMIC, ManaSourceSignature::Pathway},
    {"Temple of Enlightenment", ColorCombination::AZORIUS, ManaSourceSignature::Scry},
    {"Temple of Deceit", ColorCombination::DIMIR, ManaSourceSignature::Scry},
    {"Temple of Malice", ColorCombination::RAKDOS, ManaSourceSignature::Scry},
    {"Temple of Abandon", ColorCombination::GRUUL, ManaSourceSignature::Scry},
    {"Temple of Plenty", ColorCombination::SELESNYA, ManaSourceSignature::Scry},
    {"Temple of Silence", ColorCombination::ORZHOV, ManaSourceSignature::Scry},
    {"Temple of Epiphany", ColorCombination::IZZET, ManaSourceSignature::Scry},
    {"Temple of Malady", ColorCombination::GOLGARI, ManaSourceSignature::Scry},
    {"Temple of Triumph", ColorCombination::BOROS, ManaSourceSignature::Scry},
    {"Temple of Mystery", ColorCombination::SIMIC, ManaSourceSignature::Scry},
    {"Hallowed Fountain", ColorCombination::AZORIUS, ManaSourceSignature::Shock},
    {"Watery Grave", ColorCombination::DIMIR, ManaSourceSignature::Shock},
    {"Blood Crypt", ColorCombination::RAKDOS, ManaSourceSignature::Shock},
    {"Stomping Ground", ColorCombination::GRUUL, ManaSourceSignature::Shock},
    {"Temple Garden", ColorCombination::SELESNYA, ManaSourceSignature::Shock},
    {"Godless Shrine", ColorCombination::ORZHOV, ManaSourceSignature::Shock},
    {"Steam Vents", ColorCombination::IZZET, ManaSourceSignature::Shock},
    {"Overgrown Tomb", ColorCombination::GOLGARI, ManaSourceSignature::Shock},
    {"Sacred Foundry", ColorCombination::BOROS, ManaSourceSignature::Shock},
    {"Breeding Pool", ColorCombination::SIMIC, ManaSourceSignature::Shock},
    {"Azorius Guildgate", ColorCombination::AZORIUS, ManaSourceSignature::Guildgate},
    {"Dimir Guildgate", ColorCombination::DIMIR, ManaSourceSignature::Guildgate},
    {"Rakdos Guildgate", ColorCombination::RAKDOS, ManaSourceSignature::Guildgate},
    {"Gruul Guildgate", ColorCombination::GRUUL, ManaSourceSignature::Guildgate},
    {"Selesnya Guildgate", ColorCombination::SELESNYA, ManaSourceSignature::Guildgate},
    {"Orzhov Guildgate", ColorCombination::ORZHOV, ManaSourceSignature::Guildgate},
    {"Izzet Guildgate", ColorCombination::IZZET, ManaSourceSignature::Guildgate},
    {"Golgari Guildgate", ColorCombination::GOLGARI, ManaSourceSignature::Guildgate},
    {"Boros Guildgate", ColorCombination::BOROS, ManaSourceSignature::Guildgate},
    {"Simic Guildgate", ColorCombination::SIMIC, ManaSourceSignature::Guildgate},
    {"Glacial Fortress", ColorCombination::AZORIUS, ManaSourceSignature::Check},
    {"Drowned Catacomb", ColorCombination::DIMIR, ManaSourceSignature::Check},
    {"Dragonskull Summit", ColorCombination::RAKDOS, ManaSourceSignature::Check},
    {"Rootbound Crag", ColorCombination::GRUUL, ManaSourceSignature::Check},
    {"Sunpetal Grove", ColorCombination::SELESNYA, ManaSourceSignature::Check},
    {"Isolated Chapel", ColorCombination::ORZHOV, ManaSourceSignature::Check},
    {"Sulfur Falls", ColorCombination::IZZET, ManaSourceSignature::Check},
    {"Woodland Cemetery", ColorCombination::GOLGARI, ManaSourceSignature::Check},
    {"Clifftop Retreat", ColorCombination::BOROS, ManaSourceSignature::Check},
    {"Hinterland Harbor", ColorCombination::SIMIC, ManaSourceSignature::Check},
    {"Meandering River", ColorCombination::AZORIUS, ManaSourceSignature::Generic},
    {"Submerged Boneyard", ColorCombination::DIMIR, ManaSourceSignature::Generic},
    {"Cinder Barrens", ColorCombination::RAKDOS, ManaSourceSignature::Generic},
    {"Timber Gorge", ColorCombination::GRUUL, ManaSourceSignature::Generic},
    {"Tranquil Expanse", ColorCombination::SELESNYA, ManaSourceSignature::Generic},
    {"Forsaken Sanctuary", ColorCombination::ORZHOV, ManaSourceSignature::Generic},
    {"Highland Lake", ColorCombination::IZZET, ManaSourceSignature::Generic},
    {"Foul Orchard", ColorCombination::GOLGARI, ManaSourceSignature::Generic},
    {"Stone Quarry", ColorCombination::BOROS, ManaSourceSignature::Generic},
    {"Woodland Stream", ColorCombination::SIMIC, ManaSourceSignature::Generic},
    {"Flooded Strand", ColorCombination::AZORIUS, ManaSourceSignature::Fetch},
    {"Polluted Delta", ColorCombination::DIMIR, ManaSourceSignature::Fetch},
    {"Bloodstained Mire", ColorCombination::RAKDOS, ManaSourceSignature::Fetch},
    {"Wooded Foothills", ColorCombination::GRUUL, ManaSourceSignature::Fetch},
    {"Windswept Heath", ColorCombination::SELESNYA, ManaSourceSignature::Fetch},
    {"Marsh Flats", ColorCombination::ORZHOV, ManaSourceSignature::Fetch},
    {"Scalding Tarn", ColorCombination::IZZET, ManaSourceSignature::Fetch},
    {"Verdant Catacombs", ColorCombination::GOLGARI, ManaSourceSignature::Fetch},
    {"Arid Mesa", ColorCombination::BOROS, ManaSourceSignature::Fetch},
    {"Misty Rainforest", ColorCombination::SIMIC, ManaSourceSignature::Fetch},
    {"Razortide Bridge", ColorCombination::AZORIUS, ManaSourceSignature::Artifact},
    {"Mistvault Bridge", ColorCombination::DIMIR, ManaSourceSignature::Artifact},
    {"Drossforge Bridge", ColorCombination::RAKDOS, ManaSourceSignature::Artifact},
    {"Slagwoods Bridge", ColorCombination::GRUUL, ManaSourceSignature::Artifact},
    {"Thornglint Bridge", ColorCombination::SELESNYA, ManaSourceSignature::Artifact},
    {"Goldmire Bridge", ColorCombination::ORZHOV, ManaSourceSignature::Artifact},
    {"Silverbluff Bridge", ColorCombination::IZZET, ManaSourceSignature::Artifact},
    {"Darkmoss Bridge", ColorCombination::GOLGARI, ManaSourceSignature::Artifact},
    {"Rustvale Bridge", ColorCombination::BOROS, ManaSourceSignature::Artifact},
    {"Tanglepool Bridge", ColorCombination::SIMIC, ManaSourceSignature::Artifact},
    {"Mystic Gate", ColorCombination::AZORIUS, ManaSourceSignature::Filter},
    {"Sunken Ruins", ColorCombination::DIMIR, ManaSourceSignature::Filter},
    {"Graven Cairns", ColorCombination::RAKDOS, ManaSourceSignature::Filter},
    {"Fire-Lit Thicket", ColorCombination::GRUUL, ManaSourceSignature::Filter},
    {"Wooded Bastion", ColorCombination::SELESNYA, ManaSourceSignature::Filter},
    {"Fetid Heath", ColorCombination::ORZHOV, ManaSourceSignature::Filter},
    {"Cascade Bluffs", ColorCombination::IZZET, ManaSourceSignature::Filter},
    {"Twilight Mire", ColorCombination::GOLGARI, ManaSourceSignature::Filter},
    {"Rugged Prairie", ColorCombination::BOROS, ManaSourceSignature::Filter},
    {"Flooded Grove", ColorCombination::SIMIC, ManaSourceSignature::Filter},
    {"Azorius Chancery", ColorCombination::AZORIUS, ManaSourceSignature::Bounce},
    {"Dimir Aqueduct", ColorCombination::DIMIR, ManaSourceSignature::Bounce},
    {"Rakdos Carnarium", ColorCombination::RAKDOS, ManaSourceSignature::Bounce},
    {"Gruul Turf", ColorCombination::GRUUL, ManaSourceSignature::Bounce},
    {"Selesnya Sanctuary", ColorCombination::SELESNYA, ManaSourceSignature::Bounce},
    {"Orzhov Basilica", ColorCombination::ORZHOV, ManaSourceSignature::Bounce},
    {"Izzet Boilerworks", ColorCombination::IZZET, ManaSourceSignature::Bounce},
    {"Golgari Rot Farm", ColorCombination::GOLGARI, ManaSourceSignature::Bounce},
    {"Boros Garrison", ColorCombination::BOROS, ManaSourceSignature::Bounce},
    {"Simic Growth Chamber", ColorCombination::SIMIC, ManaSourceSignature::Bounce},
    {"Sea of Clouds", ColorCombination::AZORIUS, ManaSourceSignature::Battlebond},
    {"Morphic Pool", ColorCombination::DIMIR, ManaSourceSignature::Battlebond},
    {"Luxury Suite", ColorCombination::RAKDOS, ManaSourceSignature::Battlebond},
    {"Spire Garden", ColorCombination::GRUUL, ManaSourceSignature::Battlebond},
    {"Bountiful Promenade", ColorCombination::SELESNYA, ManaSourceSignature::Battlebond},
    {"Vault of Champions", ColorCombination::ORZHOV, ManaSourceSignature::Battlebond},
    {"Training Center", ColorCombination::IZZET, ManaSourceSignature::Battlebond},
    {"Undergrowth Stadium", ColorCombination::GOLGARI, ManaSourceSignature::Battlebond},
    {"Spectator Seating", ColorCombination::BOROS, ManaSourceSignature::Battlebond},
    {"Rejuvenating Springs", ColorCombination::SIMIC, ManaSourceSignature::Battlebond},
    {"Skycloud Expanse", ColorCombination::AZORIUS, ManaSourceSignature::OdysseyFilter},
    {"Darkwater Catacombs", ColorCombination::DIMIR, ManaSourceSignature::OdysseyFilter},
    {"Shadowblood Ridge", ColorCombination::RAKDOS, ManaSourceSignature::OdysseyFilter},
    {"Mossfire Valley", ColorCombination::GRUUL, ManaSourceSignature::OdysseyFilter},
    {"Sungrass Prairie", ColorCombination::SELESNYA, ManaSourceSignature::OdysseyFilter},
    {"Desolate Mire", ColorCombination::ORZHOV, ManaSourceSignature::OdysseyFilter},
    {"Ferrous Lake", ColorCombination::IZZET, ManaSourceSignature::OdysseyFilter},
    {"Viridescent Bog", ColorCombination::GOLGARI, ManaSourceSignature::OdysseyFilter},
    {"Sunscorched Divide", ColorCombination::BOROS, ManaSourceSignature::OdysseyFilter},
    {"Overflowing Basin", ColorCombination::SIMIC, ManaSourceSignature::OdysseyFilter},
    {"Tundra", ColorCombination::AZORIUS, ManaSourceSignature::Dual},
    {"Underground Sea", ColorCombination::DIMIR, ManaSourceSignature::Dual},
    {"Badlands", ColorCombination::RAKDOS, ManaSourceSignature::Dual},
    {"Taiga", ColorCombination::GRUUL, ManaSourceSignature::Dual},
    {"Savannah", ColorCombination::SELESNYA, ManaSourceSignature::Dual},
    {"Scrubland", ColorCombination::ORZHOV, ManaSourceSignature::Dual},
    {"Volcanic Island", ColorCombination::IZZET, ManaSourceSignature::Dual},
    {"Bayou", ColorCombination::GOLGARI, ManaSourceSignature::Dual},
    {"Plateau", ColorCombination::BOROS, ManaSourceSignature::Dual},
    {"Tropical Island", ColorCombination::SIMIC, ManaSourceSignature::Dual},
    {"Plains", ColorCombination::WHITE, ManaSourceSignature::Basic},
    {"Island", ColorCombination::BLUE, ManaSourceSignature::Basic},
    {"Swamp", ColorCombination::BLACK, ManaSourceSignature::Basic},
    {"Mountain", ColorCombination::RED, ManaSourceSignature::Basic},
    {"Forest", ColorCombination::GREEN, ManaSourceSignature::Basic},
    {"Indatha Triome", ColorCombination::ABZAN, ManaSourceSignature::TriCycle}, //White/Black/Green
    {"Spara's Headquarters", ColorCombination::BANT, ManaSourceSignature::TriCycle}, //White/Blue/Green
    {"Raffine's Tower", ColorCombination::ESPER, ManaSourceSignature::TriCycle}, //White/Blue/Black
    {"Xander's Lounge", ColorCombination::GRIXIS, ManaSourceSignature::TriCycle}, //Blue/Black/Red
    {"Savai Triome", ColorCombination::JESKAI, ManaSourceSignature::TriCycle}, //White/Blue/Red
    {"Ziatora's Proving Ground", ColorCombination::JUND, ManaSourceSignature::TriCycle}, //Black/Red/Green
    {"Raugrin Triome", ColorCombination::MARDU, ManaSourceSignature::TriCycle}, //White/Black/Red
    {"Jetmir's Garden", ColorCombination::NAYA, ManaSourceSignature::TriCycle}, //White/Red/Green
    {"Zagoth Triome", ColorCombination::SULTAI, ManaSourceSignature::TriCycle}, //Blue/Black/Green
    {"Ketria Triome", ColorCombination::TEMUR, ManaSourceSignature::TriCycle}, //Blue/Red/Green
    {"Seaside Citadel", ColorCombination::BANT, ManaSourceSignature::Tri}, //White/Blue/Green
    {"Arcane Sanctum", ColorCombination::ESPER, ManaSourceSignature::Tri}, //White/Blue/Black
    {"Crumbling Necropolis", ColorCombination::GRIXIS, ManaSourceSignature::Tri}, //Blue/Black/Red
    {"Savage Lands", ColorCombination::JUND, ManaSourceSignature::Tri}, //Black/Red/Green
    {"Jungle Shrine", ColorCombination::NAYA, ManaSourceSignature::Tri}, //White/Red/Green
    {"Nomad Outpost", ColorCombination::MARDU, ManaSourceSignature::Tri}, //White/Black/Red
    {"Sandsteppe Citadel", ColorCombination::ABZAN, ManaSourceSignature::Tri}, //White/Black/Green
    {"Opulent Palace", ColorCombination::SULTAI, ManaSourceSignature::Tri}, //Blue/Black/Green
    {"Frontier Bivouac", ColorCombination::TEMUR, ManaSourceSignature::Tri}, //Blue/Red/Green
    {"Mystic Monastery", ColorCombination::JESKAI, ManaSourceSignature::Tri}, //White/Blue/Red
};